version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  postgresql:
    image: postgres:16-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_USER}
      POSTGRES_USER: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./dump:/home/dump
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  internal:
    name: ${APP_NAME}-net
